/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linhnd.views;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import linhnd.daos.UserDAO;
import linhnd.dtos.UserDTO;
import linhnd.hash.CheckData;

/**
 *
 * @author Duc Linh
 */
public class AdminJFrame extends javax.swing.JFrame {
    DefaultTableModel tblModelAll = null;
    DefaultTableModel tblModelAdmin = null;
    DefaultTableModel tblModelUser = null;
    

    /**
     * Creates new form AdminJFrame
     */
    public AdminJFrame() {
        initComponents();
        tblModelAll = (DefaultTableModel) table_All.getModel();
        tblModelAdmin = (DefaultTableModel) table_Admin.getModel();
        tblModelUser = (DefaultTableModel) table_User.getModel();
        FirstController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        J1 = new javax.swing.JTabbedPane();
        jPanel_All = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_All = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Admin = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_User = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txt_seach = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_UserID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radio_admin = new javax.swing.JRadioButton();
        radio_user = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txt_PhotoName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_All.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "UserName", "Email", "Phone", "PhotoName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_All.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_AllMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_All);
        if (table_All.getColumnModel().getColumnCount() > 0) {
            table_All.getColumnModel().getColumn(0).setMinWidth(20);
            table_All.getColumnModel().getColumn(0).setPreferredWidth(20);
            table_All.getColumnModel().getColumn(4).setMinWidth(20);
            table_All.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel_AllLayout = new javax.swing.GroupLayout(jPanel_All);
        jPanel_All.setLayout(jPanel_AllLayout);
        jPanel_AllLayout.setHorizontalGroup(
            jPanel_AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );
        jPanel_AllLayout.setVerticalGroup(
            jPanel_AllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AllLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        J1.addTab("All", jPanel_All);

        table_Admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "userID", "userName", "Email", "Phone", "PhotoName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_AdminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_Admin);
        if (table_Admin.getColumnModel().getColumnCount() > 0) {
            table_Admin.getColumnModel().getColumn(0).setMinWidth(20);
            table_Admin.getColumnModel().getColumn(0).setPreferredWidth(20);
            table_Admin.getColumnModel().getColumn(4).setMinWidth(20);
            table_Admin.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        J1.addTab("Admin", jPanel2);

        table_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "UserName", "Emaill", "Phone", "PhotoName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_UserMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_User);
        if (table_User.getColumnModel().getColumnCount() > 0) {
            table_User.getColumnModel().getColumn(0).setMinWidth(20);
            table_User.getColumnModel().getColumn(0).setPreferredWidth(20);
            table_User.getColumnModel().getColumn(4).setMinWidth(20);
            table_User.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        J1.addTab("User", jPanel3);

        jButton1.setText("Seach");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_seach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_seachKeyPressed(evt);
            }
        });

        jLabel1.setText("User Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MANAGER USER");

        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel3.setText("IdUser :");

        txt_UserID.setText("userid");

        jLabel5.setText("UserName :");

        txt_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserNameActionPerformed(evt);
            }
        });

        jLabel6.setText("Email :");

        jLabel7.setText("Phone :");

        jLabel8.setText("Role :");

        buttonGroup1.add(radio_admin);
        radio_admin.setText("Admin");
        radio_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_adminActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_user);
        radio_user.setText("User");
        radio_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_userActionPerformed(evt);
            }
        });

        jLabel9.setText("PhotoName :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(radio_admin)
                        .addGap(29, 29, 29)
                        .addComponent(radio_user))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_UserID)
                        .addComponent(txt_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(txt_Email)
                        .addComponent(txt_Phone)
                        .addComponent(txt_PhotoName)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_UserID))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_PhotoName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_admin)
                    .addComponent(radio_user)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36))
        );

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Change Password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Create User ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Managar Promotion");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txt_seach, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_seach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginJFrame lg = new LoginJFrame();
        lg.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String textSeach = txt_seach.getText();
        if (!textSeach.equals("")) {
            try {
                UserDAO dao = new UserDAO();
                List<UserDTO> listSeach = dao.searhByName(textSeach.trim());
                showAllUser(listSeach);
                J1.setSelectedIndex(0);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Input userName you want to seach !");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserNameActionPerformed

    private void radio_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_userActionPerformed

    private void radio_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_adminActionPerformed

    private void table_AllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_AllMouseClicked
        try {
            int row = table_All.getSelectedRow();
            String userId = (String) tblModelAll.getValueAt(row, 0);
            UserDAO dao = new UserDAO();
            UserDTO dto = dao.getOneUser(userId);
            String role = dao.getRoleByuserID(userId);
            txt_UserID.setText(dto.getIdUser());
            txt_UserName.setText(dto.getUserName());
            txt_Email.setText(dto.getEmail());
            txt_Phone.setText(dto.getPhone());
            txt_PhotoName.setText(dto.getPhotoName());
            if (role.equals("admin")) {
                radio_admin.setSelected(true);
            }else if(role.equals("user")){
                radio_user.setSelected(true);
            }else{
                radio_admin.setSelected(false);
                radio_user.setSelected(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_table_AllMouseClicked

    private void table_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_AdminMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_table_AdminMouseClicked

    private void table_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_UserMouseClicked
        
    }//GEN-LAST:event_table_UserMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int row = table_User.getSelectedRow();
            if (row < 0) {
                JOptionPane.showMessageDialog(this, "Ples Select user in tab User before Delete !");
            } else {
                String userID = (String) tblModelUser.getValueAt(row, 0);
                UserDAO dao = new UserDAO();
                if (dao.deleteUser(userID)) {
                    JOptionPane.showMessageDialog(this, "Delete sucessful !");
                    FirstController();
                } else {
                    JOptionPane.showMessageDialog(this, "Delete fail ! ");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String idUser = txt_UserID.getText();
        String userName = txt_UserName.getText();
        String Email = txt_Email.getText();
        String phone = txt_Phone.getText();
        String photoName = txt_PhotoName.getText();
        String role = "";
        if (radio_admin.isSelected()) {
            role = "admin";
        } else if (radio_user.isSelected()) {
            role = "user";
        }
        String error = "";
        CheckData check = new CheckData();
        if (!check.checkEmail(Email)) {
            error = error + " Email error";
        }
        if (!check.checkUserName(userName)) {
            error = error + ", UserName error";
        }
        if (phone.equals("")) {
            error = error + ", Phone can not balnk";
        }
        if (photoName.equals("")) {
            error = error + ", PhotoName can not blank";
        }
        if (error.equals("")) {
            try {
                 UserDAO dao = new UserDAO();
                 UserDTO dto = new UserDTO(idUser, userName, Email, phone, photoName);
                 if (dao.updateUser(dto, role)) {
                    JOptionPane.showMessageDialog(this, "Update sucessful !");
                    FirstController();
                }else{
                     JOptionPane.showConfirmDialog(this, "Fail !");
                 }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, error);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CreateUser cre = new CreateUser();
        cre.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_seachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_seachKeyPressed
        String textSeach = txt_seach.getText();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!textSeach.equals("")) {
                try {
                    UserDAO dao = new UserDAO();
                    List<UserDTO> listSeach = dao.searhByName(textSeach.trim());
                    showAllUser(listSeach);
                    J1.setSelectedIndex(0);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showConfirmDialog(this, "Input userName you want to seach !");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_seachKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Promotion pro = new Promotion();
        pro.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ChangePassword cg = new ChangePassword();
        cg.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJFrame().setVisible(true);
            }
        });
    }
    public void FirstController(){
        try {
            UserDAO dao = new UserDAO();
            List<UserDTO> dtoList = dao.getAllUser();
            List<UserDTO> dtoListAdmin = dao.getListAdmin();
            List<UserDTO> dtoListUser = dao.getListUser();
            showAllUser(dtoList);
            showAdmin(dtoListAdmin);
            showUser(dtoListUser);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void showAllUser(List<UserDTO> list) throws Exception{
        tblModelAll.setRowCount(0);
        for (UserDTO userDTO : list) {
            tblModelAll.addRow(userDTO.toVector());
        }  
    }
    public void showAdmin(List<UserDTO> list) throws Exception{
        tblModelAdmin.setRowCount(0);
        for (UserDTO userDTO : list) {
            tblModelAdmin.addRow(userDTO.toVector());
        }  
    }
    public void showUser(List<UserDTO> list) throws Exception{
        tblModelUser.setRowCount(0);
        for (UserDTO userDTO : list) {
            tblModelUser.addRow(userDTO.toVector());
        }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane J1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_All;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radio_admin;
    private javax.swing.JRadioButton radio_user;
    private javax.swing.JTable table_Admin;
    private javax.swing.JTable table_All;
    private javax.swing.JTable table_User;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Phone;
    private javax.swing.JTextField txt_PhotoName;
    private javax.swing.JLabel txt_UserID;
    private javax.swing.JTextField txt_UserName;
    private javax.swing.JTextField txt_seach;
    // End of variables declaration//GEN-END:variables
}
